// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqOWDszCGjXpiJ_OF4hb0mHUxY5mf8gQI',
    appId: '1:279348218238:web:c7d2c73c328239efcc0b2f',
    messagingSenderId: '279348218238',
    projectId: 'discover-me-f0a95',
    authDomain: 'discover-me-f0a95.firebaseapp.com',
    storageBucket: 'discover-me-f0a95.firebasestorage.app',
    measurementId: 'G-9K8QXQGY4H',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKWIhZlZIhZUy31Q1ifIghXtW2Y6L5sds',
    appId: '1:279348218238:ios:300e293eb7945fc5cc0b2f',
    messagingSenderId: '279348218238',
    projectId: 'discover-me-f0a95',
    storageBucket: 'discover-me-f0a95.firebasestorage.app',
    iosBundleId: 'com.example.discoverMe',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqOWDszCGjXpiJ_OF4hb0mHUxY5mf8gQI',
    appId: '1:279348218238:web:c7d2c73c328239efcc0b2f',
    messagingSenderId: '279348218238',
    projectId: 'discover-me-f0a95',
    authDomain: 'discover-me-f0a95.firebaseapp.com',
    storageBucket: 'discover-me-f0a95.firebasestorage.app',
    measurementId: 'G-9K8QXQGY4H',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKWIhZlZIhZUy31Q1ifIghXtW2Y6L5sds',
    appId: '1:279348218238:ios:300e293eb7945fc5cc0b2f',
    messagingSenderId: '279348218238',
    projectId: 'discover-me-f0a95',
    storageBucket: 'discover-me-f0a95.firebasestorage.app',
    iosBundleId: 'com.example.discoverMe',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjcbPG42nni7WYkyEuEjSUNOcPbq-hAWs',
    appId: '1:279348218238:android:24eaefa4c761ed00cc0b2f',
    messagingSenderId: '279348218238',
    projectId: 'discover-me-f0a95',
    storageBucket: 'discover-me-f0a95.firebasestorage.app',
  );

}